---
- name: add path to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ primary_host_ip }} {{ primary_host_name }}"
    state: present
  when: use_hosts_file

- name: add path to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ secondary_host_ip }} {{ secondary_host_name }}"
    state: present
  when: use_hosts_file

- name: Install the package "mssql-server-ha"
  yum: name=mssql-server-ha state=present
  when: ansible_distribution == "CentOS"

- name: Install the package "mssql-server-ha"
  apt:
    name: mssql-server-ha
    allow_unauthenticated: true
    update_cache: yes
    state: present
  when: ansible_os_family == "Debian"

- name: Stop sql server if it was already running and initialized
  service: name=mssql-server state=stopped
  register: res

- name: enable HA on sql server
  shell: /opt/mssql/bin/mssql-conf set hadr.hadrenabled  1

- name: Enable enable 5022 on firewall
  firewalld:
    port: 5022/tcp
    permanent: true
    state: enabled
    zone: public
  notify: restart-firewalld
  when: ansible_distribution == "CentOS"

- name: Start sql server
  service: name=mssql-server state=started enabled=yes

